TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.0
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  holonomic_robot: true

  xy_goal_tolerance: .8
  yaw_goal_tolerance: 1.57
  sim_time: 4
