ObstacleAvoidanceController:
  GenAndTest: {collision_details: true, dt: 0.1, num_threads: 5, parallelism: true,
    tf: 10.0}
  idle_eval: true
  min_ttc: 7.0
  min_tte: 5.0
  num_paths: 5
  path_limits: 0.8
  v_des: 0.25
  wander: false
depth_image_cc_wrapper:
  depth_image_collision_checker: {floor_tolerance: 0.03, model_type: 9, param_name: /simplified_robot_description,
    robot_height: 0.48, robot_radius: 0.178, safety_expansion: 0.02, show_im: true}
  depth_image_topic: /camera/depth/image_raw
  depth_info_topic: /camera/depth/camera_info
trajectory_controller: {k_drive_x: 1.0, k_drive_y: 1.0, k_turn: 1.0, odom_spinner: false}
