DWAPlannerROS:
  max_vel_x:                 0.55
  min_vel_x:                 0.0
  max_vel_theta:             0.3
  min_in_place_vel_theta:    0.4

  acc_lim_theta:             3.2
  acc_lim_x:                 2.5
  acc_lim_y:                 2.5
  yaw_goal_tolerance:        1.57
  holonomic_robot:           true
  sim_time:                  3

  xy_goal_tolerance:         0.8
  yaw_goal_tolerance:        1.57
  use_dwa:                 true
