    
## Forward simulation parameters
angular_sim_granularity: 0.1
sim_granularity: 0.1 # 0.025

## Goal Tolerance Parameters
# latch_xy_goal_tolerance: false


global_frame_id: odom


## Differential-drive robot configuration - necessary?
holonomic_robot: false
