EBandPlannerROS:

#TRAJECTORY CONTROL
 differential_drive: true
 max_acceleration: 1.0

# velocity limits
 max_vel_lin: 0.5
 max_vel_th: 5.0
 min_vel_lin: 0.0
 min_vel_th: 0.0
 min_in_place_vel_th: 0.0
 in_place_trans_vel: 0.0
 sim_time: 10
# goal tolerance
 xy_goal_tolerance: 0.8
 yaw_goal_tolerance: 1.57

# angular velocity PID
 k_prop_: 0.75

#eband parameters


