# Parameters for global costmap behavior
global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 5.0         # Hz
  static_map: true              # Get the map from map_server and don't update it