global_frame: map
robot_base_frame: base_footprint
update_frequency: 1.0
publish_frequency: 0.5
static_map: true
transform_tolerance: 0.5
plugins:
 - {name: static_layer,            type: "costmap_2d::StaticLayer"}
# - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
 - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

robot_radius: 0.25

static_layer:
  enabled:              true
  map_topic:  groundtruth/map
  
#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

