local_costmap:
  global_frame: odom            # Local costmap is relative to odom frame
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true          # Stay centered on the robot as it moves
  width: 10.                    # meters
  height: 10.0                   # meters
  resolution: 0.05              # meters / cell
