PotentialGapPlanner:
    min_resoln: 10
    gap_diff: 0.1
    global_plan_lookup_increment: 75
    goal_tolerance: 0.2
    global_plan_change_tolerance: 0.1
    follow_the_gap_visparsing: True
    close_gap_visparsing: True

    epsilon2: 0.18
    epsilon1: 0.18

    niGen_s: True
    config_sanity_val: 100
