local_costmap: ##TODO: clear this whole thing
  obstacle_layer:
    observation_sources: false


global_costmap:
  obstacle_layer:
    collisions:
      topic: /move_base/EgocylindricalPipsDWAPlannerROS/egocylindrical_image_cc_wrapper/egocylindrical_image_collision_checker/collisions
  

