odom1: odometry/gps
odom1_config: [true,  true,  false,
                                false, false, false,
                                false, false, false,
                                false, false, false,
                                false, false, false]
odom1_differential: false

