local_costmap: ##TODO: clear this whole thing
  robot_base_frame: base_link
  global_frame:     world
  robot_radius:     .4
  obstacle_layer:
    max_obstacle_height:  1.2
    min_obstacle_height:  0.8
    origin_z:             0.8
    z_resolution:         0.2
    z_voxels:             2
    unknown_threshold:    15
    mark_threshold:       0
    combination_method:   1
    track_unknown_space:  false    #true needed for disabling global path planning through unknown space
    obstacle_range: 2.5
    raytrace_range: 3.0

    publish_voxel_map: false
    observation_sources:  scan bump collisions
    scan:
      data_type: LaserScan
      topic: scan
      marking: true
      clearing: true
      max_obstacle_height:  1.2
      min_obstacle_height:  0.8


odom_topic: /ground_truth/state
base_frame_id: base_link

global_costmap:
  robot_base_frame: base_link
  global_frame:     world
  robot_radius:     .4
  obstacle_layer:
    max_obstacle_height:  1.2
    min_obstacle_height:  0.8
    origin_z:             0.8
    z_resolution:         0.2
    z_voxels:             2
    unknown_threshold:    15
    mark_threshold:       0
    combination_method:   1
    track_unknown_space:  false    #true needed for disabling global path planning through unknown space
    obstacle_range: 2.5
    raytrace_range: 3.0

    publish_voxel_map: false
    observation_sources:  scan bump collisions
    scan:
      data_type: LaserScan
      topic: scan
      marking: true
      clearing: true
      max_obstacle_height:  1.2
      min_obstacle_height:  0.8
  
  
EgocylindricalPipsDWAPlannerROS:
  global_frame_id:  world
  inscribed_radius: .4
  inflation_radius: 1.0
  inflation_scaling_factor: 5.0
  path_distance_bias: 24
  goal_distance_bias: 24
  forward_point_distance: .45
  egocircle_scale: 30
